In [ ]:
import pandas as pd

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/student-alcohol-consumption")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/uciml/student-alcohol-consumption/2.archive...

100%|██████████| 18.4k/18.4k [00:00<00:00, 12.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/uciml/student-alcohol-consumption/versions/2

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "student-mat.csv"

df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "uciml/student-alcohol-consumption",
  file_path,
)

Using Colab cache for faster access to the 'student-alcohol-consumption' dataset.

In [ ]:
df.shape

(395, 33)

In [ ]:
pd.DataFrame({
    'Nº': range(1, len(df.columns) + 1),
    'Atributo': df.columns,
    'Tipo': df.dtypes.values
})

    Nº    Atributo    Tipo
0    1      school  object
1    2         sex  object
2    3         age   int64
3    4     address  object
4    5     famsize  object
5    6     Pstatus  object
6    7        Medu   int64
7    8        Fedu   int64
8    9        Mjob  object
9   10        Fjob  object
10  11      reason  object
11  12    guardian  object
12  13  traveltime   int64
13  14   studytime   int64
14  15    failures   int64
15  16   schoolsup  object
16  17      famsup  object
17  18        paid  object
18  19  activities  object
19  20     nursery  object
20  21      higher  object
21  22    internet  object
22  23    romantic  object
23  24      famrel   int64
24  25    freetime   int64
25  26       goout   int64
26  27        Dalc   int64
27  28        Walc   int64
28  29      health   int64
29  30    absences   int64
30  31          G1   int64
31  32          G2   int64
32  33          G3   int64

In [ ]:
df.head(15)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16